I2P_LAPP/Areas/Users/Controllers/RoleManagerController.cs
using Infinite.LAPP.Domain.DomainModel;
using Infinite.LAPP.Domain.IRepository;
using Infinite.LAPP.EntityModel;
using Infinite.LAPP.Repository.QueryObjects;
using Infinite.LAPP.WebFront.Areas.Users.Models;
using Infinite.LAPP.WebFront.Controllers;
using Infinite.LAPP.WebFront.MVCInfrastructure.ClaimsSecurity;
using Infinite.LAPP.WebFront.MVCInfratructure.MappingLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Permissions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.IdentityModel.Services;


namespace Infinite.LAPP.WebFront.Areas.Users.Controllers
{
    [Authorize]
    public class RoleManagerController : BaseController
    {
        private readonly IRoleRepository _roleRepository;
        private readonly IModuleRepository _moduleRepository;
        private readonly IRolePermissionRepository _rolePermissionRepository;
        private readonly ListRolesQuery _query;

        /// <summary>
        /// Initializes a new instance of the <see cref="RoleManagerController"/> class.
        /// </summary>
        /// <param name="roleRepository">The i role repository.</param>
        /// <param name="moduleRepository">The module repository.</param>
        /// <param name="rolePermissionRepository">The role permission repository.</param>
        public RoleManagerController(IRoleRepository roleRepository, IModuleRepository moduleRepository,
            IRolePermissionRepository rolePermissionRepository, ListRolesQuery query)
        {
            this._roleRepository = roleRepository;
            this._moduleRepository = moduleRepository;
            this._rolePermissionRepository = rolePermissionRepository;
            this._query = query;
        }

        /// <summary>
        /// This action method is used to get view for creating new role.
        /// </summary>
        /// <returns></returns>
        [CustomClaimAttribute(SecurityAction.Demand, Resource = "Role Management", Value = "canAddRole")]
        [MappingFilterAttribute(typeof(List<Module>), typeof(CreateRoleViewModel))]
        public ActionResult Create()
        {
            var moduleList = _moduleRepository.GetAll().ToList();

            return View(moduleList);
        }

        /// <summary>
        /// This action method is used to insert newly created role in DB along with it's access rights on modules.
        /// </summary>
        /// <param name="model">user role view model</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Create(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userRole = model.ConvertToDomainModel();
                _rolePermissionRepository.Insert(userRole);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        /// <summary>
        /// This action method is used to get all the roles present in DB.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [CustomClaimAttribute(SecurityAction.Demand, Resource = "Role Management", Value = "canViewRole")]
        [MappingFilterAttribute(typeof(List<vw_RoleUserCount>), typeof(RoleManagerViewModel))]
        public ActionResult Index()
        {
            var roles = _query.Execute();

            return View(roles);
        }

        /// <summary>
        /// This action method is use to get view for editing existing role.
        /// </summary>
        /// <param name="id">role id</param>
        /// <returns></returns>
        [HttpGet]
        [CustomClaimAttribute(SecurityAction.Demand, Resource = "Role Management", Value = "canEditRole")]
        [MappingFilterAttribute(typeof(Permission), typeof(EditRoleViewModel))]
        public async Task<ActionResult> Edit(int id)
        {
            var userRole = _rolePermissionRepository.GetById(id);

            return View(userRole);
        }

        /// <summary>
        /// This action method is use to update an existing role record.
        /// </summary>
        /// <param name="model">existing user role</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Edit(EditRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userRole = model.ConvertToDomainModel();
                _rolePermissionRepository.Update(userRole);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        [CustomClaimAttribute(SecurityAction.Demand, Resource = "Role Management", Value = "canViewRole")]
        [MappingFilterAttribute(typeof(Permission), typeof(EditRoleViewModel))]
        public ActionResult Profile(int id)
        {
            var userRole = _rolePermissionRepository.GetById(id);

            return View(userRole);
        }

        /// <summary>
        /// This method is used to check that the role name entered by the user in unique or not.
        /// </summary>
        /// <param name="roleName">role name</param>
        /// <param name="roleId">role id</param>
        /// <returns></returns>
        public JsonResult IsUniqueRoleName(string name, int roleId = 0)
        {
            var result = _rolePermissionRepository.IsValueUnique(
                Helpers.CommonMethods.GetPropertyName(() => new Permission().RoleName), name, roleId);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This method is used to check that the display role name entered by the user in unique or not.
        /// </summary>
        /// <param name="displayName">role display name</param>
        /// <param name="roleId">role id</param>
        /// <returns></returns>
        public JsonResult IsUniqueDisplayRoleName(string displayName, int roleId = 0)
        {
            var result = _rolePermissionRepository.IsValueUnique(
                Helpers.CommonMethods.GetPropertyName(() => new Permission().RoleDisplayName), displayName, roleId);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

       
    }
}

I2P_LAPP/Areas/Users/Controllers/UserController.cs
using Infinite.LAPP.Domain.DomainModel;
using Infinite.LAPP.Domain.IRepository;
using Infinite.LAPP.WebFront.Areas.Users.Models;
using Infinite.LAPP.WebFront.Controllers;
using Infinite.LAPP.WebFront.MVCInfrastructure.ClaimsSecurity;
using Infinite.LAPP.WebFront.MVCInfrastructure.IdentityFramework;
using Infinite.LAPP.WebFront.MVCInfratructure.MappingLayer;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Permissions;
using System.Web.Mvc;

namespace Infinite.LAPP.WebFront.Areas.Users.Controllers
{
     [Authorize]
    public class UserController : BaseController
    {
        private readonly CustomIdentityUserManager _userManager;
        private readonly IUserRepository _userRep;

        public UserController(CustomIdentityUserManager userManager, IUserRepository userRep)
        {
            if (userManager == null)
                throw new ArgumentNullException("userManager is null");
            if (userRep == null)
                throw new ArgumentNullException("userRep is null");

            this._userManager = userManager;
            this._userRep = userRep;
        }

        [CustomClaimAttribute(SecurityAction.Demand, Resource = "User Management", Value = "canViewUser")]
        [MappingFilterAttribute(typeof(List<User>), typeof(List<DisplayUsersViewModel>))]
        public ActionResult Index()
        {
            return View(_userRep.GetAll());
        }

        [CustomClaimAttribute(SecurityAction.Demand, Resource = "User Management", Value = "canAddUser")]
        [MappingFilterAttribute(typeof(User), typeof(CreateUserViewModel))]
        public ActionResult Create(int id = 0, string role = null)
        {
            ViewBag.RoleId = id;
            ViewBag.Role = role;

            ViewBag.Roles = new SelectList(_userRep.GetAllRoles(), "RoleId", "RoleName");
            User user = new User() { IsActive = true };
            return View(user);
        }

        [HttpPost]
        public ActionResult Create(CreateUserViewModel model)
        {
            // hash password
            var passwordHash = _userManager.PasswordHasher.HashPassword(model.Password);

            // save to db
            _userRep.Insert(model.ToDomainModel(model, passwordHash));

            return RedirectToAction("Index");
        }

        [CustomClaimAttribute(SecurityAction.Demand, Resource = "User Management", Value = "canEditUser")]
        [MappingFilterAttribute(typeof(User), typeof(EditUserViewModel))]
        public ActionResult Edit(int id)
        {
            var user = _userRep.GetById(id);
            ViewBag.Roles = new SelectList(_userRep.GetAllRoles(), "RoleId", "RoleName", user.RoleId);
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(EditUserViewModel model)
        {
            _userRep.Update(model.ToDomainModel(model));

            return RedirectToAction("Index");
        }

        [MappingFilterAttribute(typeof(User), typeof(EditUserProfileViewModel))]
        public ActionResult EditProfile()
        {
            return View(_userRep.GetById(base.LoggedInUserId));
        }

        [HttpPost]
        public ActionResult EditProfile(EditUserProfileViewModel model)
        {
            _userRep.UpdateProfile(model.ToDomainModel(model), base.LoggedInUserId);
            return RedirectToAction("Index", "DashBoard");
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordViewModel model)
        {
            IdentityResult result = _userManager.ChangePassword(LoggedInUserId, model.OldPassword, model.NewPassword);

            if (result.Succeeded)
            {
                var userData = _userRep.GetById(LoggedInUserId);
            }
            return RedirectToAction("LogOff", "WebAccount");
        }

        [HttpGet]
        public virtual JsonResult IsEmailAvailable(CreateUserViewModel model)
        {
            return _userRep.IsEmailAvailable(model.EmailAddress)
                    ? Json(true, JsonRequestBehavior.AllowGet)
                    : Json(false, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public virtual JsonResult CheckPasssword(ChangePasswordViewModel model)
        {
            return this.IsPassswordValid(base.LoggedInUserId, model.OldPassword)
                   ? Json(true, JsonRequestBehavior.AllowGet)
                   : Json(false, JsonRequestBehavior.AllowGet);
        }

        public bool IsPassswordValid(int userId, string currentPassword)
        {
            PasswordVerificationResult result = _userManager.PasswordHasher.VerifyHashedPassword(_userRep.GetHashedPassword(userId), currentPassword);

            if (result.Equals(PasswordVerificationResult.Success))
                return true;
            return false;
        }

        [CustomClaimAttribute(SecurityAction.Demand, Resource = "User Management", Value = "canViewUser")]
        [MappingFilterAttribute(typeof(List<User>), typeof(List<DisplayUsersViewModel>))]
        public ActionResult _UserIndexView(int roleId = 0)
        {
            return View(_userRep.GetAll().Where(x => x.RoleId == roleId || roleId == 0).ToList());
        }

        [HttpGet]
        public JsonResult NotEqualToOldPassword(string NewPassword, string OldPassword)
        {
            var result = OldPassword == NewPassword ? false : true;

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

I2P_LAPP/Areas/Users/Views/RoleManager/Create.cshtml
@using Infinite.LAPP.WebFront.HtmlHelpers;
@model Infinite.LAPP.WebFront.Areas.Users.Models.CreateRoleViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAfterAdminLogin.cshtml";
}

@section HeaderSection {
    @Html.HeaderSectionHtml("Add a New Role")
}

@section ActionNav {

    @Html.TaskLinkHtml("View All Roles", "/Users/RoleManager/Index", "fa fa-user ")

}
<script>
    function formsubmit() {
        if ($("#Form").valid())
            {
                $("#Form").submit();
             }
        else {
            return false
             }
        }
    $(document).ready(function () {
        var manager = $("#managerCheckBox");
        var trainee = $("#traineeCheckBox");
        var form = $("form");
        var checkBoxErrorMessage = $("#checkBoxError");
        checkBoxErrorMessage.hide();
        trainee.prop("checked", true);
        $("#saveButton").off('click');
        $("#saveButton").on('click', function () {
            if (manager.is(":checked") == false && trainee.is(":checked") == false) { checkBoxErrorMessage.show(); return false; }
            else {
                checkBoxErrorMessage.hide();
                form.valid();
            }
        });

        $("input:checkbox").on('change', function () {
            var id = $(this).attr("id");
            if (id == $(trainee).attr("id")) {
                if (trainee.is(":checked") == true) {
                    manager.prop("checked", false);
                    checkBoxErrorMessage.hide();
                }
                else {
                    checkBoxErrorMessage.show();
                }
            }
            else if (id == $(manager).attr("id")) {
                if (manager.is(":checked") == true) {
                    trainee.prop("checked", false);
                    checkBoxErrorMessage.hide();
                }
                else {
                    checkBoxErrorMessage.show();
                }
            }
            else {
                return false;
            }
        });
    });
</script>


@using (Html.BeginForm("Create", "RoleManager", FormMethod.Post, new { id = "Form" }))
{
    @Html.AntiForgeryToken()


    @Html.ValidationSummary(true)
    <div class="section">
        <h3>Basic Details</h3>
        <p class="sub header">How should the role be identified?</p>
        <div class="row mar-top-lg">
        <div class="col-md-5">
            <div class="admin-label">@Html.LabelFor(model => model.Name)</div>
            <div class="">
                @Html.TextBoxFor(model => model.Name, new { placeholder = Html.DisplayNameFor(model => model.Name),@class = "form-control"  })
                    </div>
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
        <div class="col-md-5">
            <div class="admin-label">
                @Html.DisplayNameFor(model => model.DisplayName)
                </div>
            <div class="">
                @Html.TextBoxFor(model => model.DisplayName, new { placeholder = Html.DisplayNameFor(model => model.DisplayName),@class = "form-control"  })
            </div>
            @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="row">
        <div class="col-md-4 mar-top-lg">
            <label>@Html.DisplayNameFor(model => model.Description)</label>
            <div class="">
                @Html.TextAreaFor(model => model.Description, new { placeholder = Html.DisplayNameFor(model => model.Description), @class = "form-control marl0" })
                </div>
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger comment-err" })
            </div>
            <div class=" col-md-6 pad-top-md">
                <div class="addemp row pad-top-md">
                    <div class="col-md-offset-3 col-md-9">
                        <label class="checkbox-inline  ">
                            @Html.CheckBoxFor(m => m.IsTrainee, new { @id = "traineeCheckBox" })
                            Trainee
                        </label>
                        <label class="checkbox-inline">
                            @Html.CheckBoxFor(m => m.IsReportingManager, new { @id = "managerCheckBox" })
                            Reporting Manager
                        </label>
                    </div>
                </div>
                 <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <span id="checkBoxError" class="text-danger field-validation-error">Either one checkbox is required.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="section">
        <h3>Set Permissions</h3>
        <p class="sub header">Which <strong>Features</strong> can this role access?</p>
        <table class="table">
            <tr>
                <th class="align-left">Set Permission </th>
                <th class="align-center"><i class="fa fa-check"></i> <label>Modify</label></th>
                <th class="align-center"><i class="fa fa-file-text-o"></i> <label>Read Only</label></th>
                <th class="align-center"><i class="fa fa-times"></i> <label>Denied</label></th>
            </tr>

            @for (var i = 0; i < Model.RolePermissionList.Count; i++)
            {
                <tr>
                    <td class="align-left">
                        @Html.DisplayFor(model => Model.RolePermissionList[i].ModuleName)
                        @Html.HiddenFor(model => Model.RolePermissionList[i].ModuleId)
                        @Html.HiddenFor(model => Model.RolePermissionList[i].ModuleName)
                    </td>
                    <td class="align-center">
                        @Html.RadioButtonFor(model => model.RolePermissionList[i].AccessRights, "ReadWrite")
                    </td>
                    <td class="align-center">
                        @Html.RadioButtonFor(model => model.RolePermissionList[i].AccessRights, "ReadOnly")
                    </td>
                    <td class="align-center">
                        @Html.RadioButtonFor(model => model.RolePermissionList[i].AccessRights, "Denied")
                    </td>
                </tr>
            }
        </table>
    </div>
    <button id="confirmButton" class="btn btn-success" type="button" value="Confirm" onclick="formsubmit()">Create</button>
    @Html.CancelButtonHtml()
    @*@Html.SaveButtonHtml("Create", "create", "Role")*@
}

I2P_LAPP/Areas/Users/Views/RoleManager/Edit.cshtml
@using Infinite.LAPP.WebFront.HtmlHelpers;
@using Infinite.LAPP.Domain;
@model Infinite.LAPP.WebFront.Areas.Users.Models.EditRoleViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAfterAdminLogin.cshtml";
}
@section HeaderSection {
    @Html.HeaderSectionHtml("Edit " + @Model.Name)
}
@section ActionNav {

    @Html.TaskLinkHtml("View All Roles", @Url.Action("Index", "RoleManager"), "fa fa-user")

    @*@if (Model.Name == DomainConstants.SuperUserRole)
        {
            @Html.TaskLinkHtml("Add User", "/Users/User/Create?id=" + @Model.RoleId + "&amp;role=" + @Model.Name, "fa fa-user fa-plus")
        }*@
}

<script>

    $(document).ready(function () {
        var manager = $("#managerCheckBox");
        var trainee = $("#traineeCheckBox");
        var form = $("form");
        var checkBoxErrorMessage = $("#checkBoxError");
        checkBoxErrorMessage.hide();
        $("#saveButton").off('click');
        $("#saveButton").on('click', function () {
            if (manager.is(":checked") == false && trainee.is(":checked") == false) { checkBoxErrorMessage.show(); return false; }
            else {
                checkBoxErrorMessage.hide();
                form.valid();
            }
        });

        $("input:checkbox").on('change', function () {
            var id = $(this).attr("id");
            if (id == $(trainee).attr("id")) {
                if (trainee.is(":checked") == true) {
                    manager.prop("checked", false);
                    checkBoxErrorMessage.hide();
                }
                else {
                    checkBoxErrorMessage.show();
                }
            }
            else if (id == $(manager).attr("id")) {
                if (manager.is(":checked") == true) {
                    trainee.prop("checked", false);
                    checkBoxErrorMessage.hide();
                }
                else {
                    checkBoxErrorMessage.show();
                }
            }
            else {
                return false;
            }
        });
    });
</script>

@using (Html.BeginForm("Edit"))
{
    @Html.AntiForgeryToken()
    object textBoxOption = null;
    object permissionReadonly = null;
    <div class="section">
        <h3>Basic Details</h3>
        <p class="sub header">How should the role be identified?</p>
        @if (Model.IsPreDefinedRole)
        {
            @Html.HiddenFor(model => model.Name)
            textBoxOption = new { disabled = "true", @class = "form-control" };
        }

        @if (Model.Name == DomainConstants.SuperUserRole)
        {
            @Html.HiddenFor(model => model.IsPreDefinedRole)
            permissionReadonly = new { disabled = "true" };
        }
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.RoleId)

        <div class="row">
            <div class="col-md-6 mar-top-md mar-bottom-md">
                <div class="row">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Name, textBoxOption)
                    </div>
                    @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6  mar-top-md mar-bottom-md">
                <div class="row">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.DisplayName)
                    </div>
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.DisplayName, new { @class = "form-control" })
                    </div>
                    @Html.ValidationMessageFor(x => x.DisplayName, null, new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6  mar-top-md mar-bottom-md">
                <div class="row">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="col-md-3">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                    </div>
                    @Html.ValidationMessageFor(x => x.Description, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="addemp row pad-top-md">
                    <div class="col-md-offset-3 col-md-9">
                        <label class="checkbox-inline  ">
                            @Html.CheckBoxFor(m => m.IsTrainee, new { @id = "traineeCheckBox" })
                            Trainee
                        </label>
                        <label class="checkbox-inline">
                            @Html.CheckBoxFor(m => m.IsReportingManager, new { @id = "managerCheckBox" })
                            Reporting Manager
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <span id="checkBoxError" class="text-danger field-validation-error">Either one checkbox is required.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section">
        <h3>Set Permissions</h3>
        <p class="sub header">Which <strong>Features</strong> can this role access?</p>
        <table class="table">
            <tr>
                <th class="align-left">Set Permission </th>
                <th class="align-center"><i class="fa fa-check"></i> <label>Modify</label></th>
                <th class="align-center"><i class="fa fa-file-text-o"></i> <label>Read Only</label></th>
                <th class="align-center"><i class="fa fa-times"></i> <label>Denied</label></th>
            </tr>
            @Html.HiddenFor(model => model.RolePermissionList.FirstOrDefault().AccessRights)
            @for (var i = 0; i < Model.RolePermissionList.Count; i++)
            {
                <tr>
                    <td class="align-left">
                        @Html.DisplayFor(model => Model.RolePermissionList[i].ModuleName)
                        @Html.HiddenFor(model => Model.RolePermissionList[i].ModuleId)
                        @Html.HiddenFor(model => model.RolePermissionList[i].Id)
                        @Html.HiddenFor(model => model.RolePermissionList[i].RoleId)
                        @Html.HiddenFor(model => Model.RolePermissionList[i].ModuleName)
                    </td>
                    <td class="align-center">
                        @Html.RadioButtonFor(model => model.RolePermissionList[i].AccessRights, "ReadWrite", permissionReadonly)
                    </td>
                    <td class="align-center">
                        @Html.RadioButtonFor(model => model.RolePermissionList[i].AccessRights, "ReadOnly", permissionReadonly)
                    </td>
                    <td class="align-center">
                        @Html.RadioButtonFor(model => model.RolePermissionList[i].AccessRights, "Denied", permissionReadonly)
                    </td>
                </tr>
            }
        </table>

    </div>

    @Html.CancelButtonHtml()
    @Html.SaveButtonHtml("Save", "edit", "Role")
}

I2P_LAPP/Areas/Users/Views/RoleManager/Index.cshtml
@using Infinite.LAPP.WebFront.HtmlHelpers;
@model Infinite.LAPP.WebFront.Areas.Users.Models.RoleManagerViewModel
@{
    ViewBag.Title = "Role Management";
    Layout = "~/Views/Shared/_LayoutAfterAdminLogin.cshtml";
}
@section HeaderSection {

    @Html.HeaderSectionHtml("Access Roles and Users")
}

@section ActionNav {

    @if (Model.CanCreateNewRole)
    {
        @*@Html.TaskLinkHtml("Add New role", @Url.Action("Create", "RoleManager", new { area = "Users" }), "fa fa-address-card")*@
    }
}

<div class="row">
    <div class="col-md-12 mar-top-lg" data-remove-target="p:first">
        <div class="panel panel-success">
            <div class="panel-heading">Roles List</div>
            <table class="table">
                <thead>
                    <tr>
                        <th width="35%">Role Name</th>
                        <th width="35%">No of Users</th>
                        <th width="50%">Role Description</th>
                        @*<th width="20%">Edit Role</th>*@

                    </tr>
                </thead>
                <tbody>
                    @foreach (var m in Model.RoleViewModelList)
                    {
                        <tr>
                            <td>
                                @if (Model.CanEditRole)
                                {
                                    @Html.ActionLink(m.RoleName, "Profile", new { id = m.RoleId })


                                }
                                else
                                {
                                    @m.RoleName;

                                }
                            </td>
                            <td>

                                @if (m.UserCount == 1)
                                {
                                    <label>@m.UserCount</label>  @Html.Label(" User")
                                }
                                else if (m.UserCount > 1)
                                {
                                    <label>@m.UserCount</label> @Html.Label(" Users")
                                }
                                else
                                {
                                    @Html.Label("No User")
                                }



                            </td>

                            <td>
                                @m.RoleDescription
                            </td>
                            @*<td>
                                <a href="/Users/RoleManager/Edit/@m.RoleId" class="btn btn-primary">
                                    <i class="fa fa-edit fa-md"></i> Edit
                                </a>
                            </td>*@

                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

I2P_LAPP/Areas/Users/Views/RoleManager/Profile.cshtml
@using Infinite.LAPP.WebFront.HtmlHelpers;
@using Infinite.LAPP.Domain;
@model Infinite.LAPP.WebFront.Areas.Users.Models.EditRoleViewModel

@{
    ViewBag.Title = "Role Profile";
    Layout = "~/Views/Shared/_LayoutAfterAdminLogin.cshtml";
}

<script type="text/javascript">
    $( document ).ready(function() {
        $.ajax({
            url: '@Url.Action("_UserIndexView","User")',
            type: 'GET',
            cache: false,
            data: { roleId: @Model.RoleId }
        }).done(function(result) {
            $('#userDetails').html(result);
        })
    });
</script>

@section HeaderSection {
    @Html.HeaderSectionHtml(@Model.DisplayName)
}

@section ActionNav{
@if (Model.CanViewRole)
{
    @Html.TaskLinkHtml("View All Roles", @Url.Action("Index", "RoleManager"), "fa fa-user")
}
@if (Model.CanEditRole)
{
    @*@Html.TaskLinkHtml("Edit", "/Users/RoleManager/Edit/" + @Model.RoleId, "fa fa-edit")*@
}
@*@if (Model.CanCreateUser && Model.Name != DomainConstants.Employee)
{
    @Html.TaskLinkHtml("Add User", "/Users/User/Create?id=" + @Model.RoleId + "&amp;role=" + @Model.Name, "fa fa-user fa-add")
}*@
}



<div class="twelve wide column" id="userDetails">

</div>