I2P_LAPP/Areas/Users/Controllers/WebAccountController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Infinite.LAPP.WebFront;
using Infinite.LAPP.WebFront.Areas.Users.Models;
using Infinite.LAPP.WebFront.Controllers;
using System.Web.UI;
using Infinite.LAPP.WebFront.MVCInfrastructure.IdentityFramework;
using System.Collections.Generic;
using Microsoft.AspNet.Identity.EntityFramework;
using Infinite.LAPP.Domain.Service;
using Infinite.LAPP.WebFront.MVCInfratructure.MappingLayer;
using Infinite.LAPP.Domain.DomainModel;
using Infinite.LAPP.Repository;
using AutoMapper;
using Infinite.LAPP.Domain.IRepository;
using System.DirectoryServices;

namespace Infinite.LAPP.WebFront.Areas.Users.Controllers
{
    [Authorize]
    public class WebAccountController : BaseController
    {
        private IUserRepository _userRep;
        private CustomIdentitySignInManager _signInManager;
        private CustomIdentityUserManager _userManager;
        private CustomIdentityRoleManager _roleManager;
        private IAuthenticationManager _authenticationManager;
        private PermissionService _permissionService;


        public WebAccountController(CustomIdentityUserManager userManager, CustomIdentitySignInManager signInManager, IAuthenticationManager authenticationManager,
                                    PermissionService permissionService, CustomIdentityRoleManager roleManager, IUserRepository userRep)
        {
            if (userManager == null)
                throw new ArgumentNullException("userManager is null");
            if (signInManager == null)
                throw new ArgumentNullException("signInManager is null");
            if (authenticationManager == null)
                throw new ArgumentNullException("authenticationManager is null");
            if (permissionService == null)
                throw new ArgumentNullException("permissionService is null");
            if (roleManager == null)
                throw new ArgumentNullException("roleManager is null");
            if (userRep == null)
                throw new ArgumentNullException("userRep is null");

            _userManager = userManager;
            _signInManager = signInManager;
            _authenticationManager = authenticationManager;
            _permissionService = permissionService;
            _roleManager = roleManager;
            _userRep = userRep;

        }
        private bool HasPassword
        {
            get
            {
                var user = _userManager.FindById(base.LoggedInUserId);
                if (user != null)
                {
                    return user.PasswordHash != null;
                }
                return false;
            }
        }


        //
        // GET: /WebAccount/Login
        [AllowAnonymous]
        [OutputCache(NoStore = true, Location = OutputCacheLocation.None)]
        public ActionResult Login(string returnUrl)
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Dashboard", new { area = "Users" });
            }
            else
            {
                ViewBag.ReturnUrl = returnUrl;
            }

            return View();
        }

        //
        // POST: /WebAccount/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            var result = SignInStatus.Failure;
            var userdata = _userRep.GetUserByUserName(model.Email);
            if (userdata!=null)
            {
                var username = userdata.FirstName + ' ' + userdata.LastName;


                // build UID string
                String CN = "cn=" + username + ",ou=Users,ou=Infinite-MDC,dc=ics,dc=global";
                // assign password

                // define LDAP connection
                DirectoryEntry root = new DirectoryEntry(
                    "LDAP://inmdcs0001.ics.global:389", CN, model.Password,
                    System.DirectoryServices.AuthenticationTypes.None);
                try
                {

                    // attempt to use LDAP connection
                    object connected = root.NativeObject;

                    // no exception, login successful
                    result = SignInStatus.Success;
                }
                catch (Exception ex)
                {
                    // exception thrown, login failed
                    result = SignInStatus.Failure;
                }
            }
            //comment
            //result = SignInStatus.Success;
            
           
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            //var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                     //return RedirectToAction("Index", "Dashboard");
                    return RedirectToAction("SetUserClaims", new { email = model.Email, returnUrl = returnUrl, password = model.Password });
                case SignInStatus.LockedOut:
                    ModelState.AddModelError("", "User locked Out");
                    return View();
                case SignInStatus.Failure:
                    ModelState.AddModelError("", "Invalid UserId/Password");
                    return View(model);
                case SignInStatus.RequiresVerification:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        /// <summary>
        /// Sets the user claims.
        /// </summary>
        /// <param name="email">The email.</param>
        /// <param name="returnUrl">The return URL.</param>
        /// <returns></returns>
         [AllowAnonymous]
        public async Task<ActionResult> SetUserClaims(string email, string returnUrl, string password)
        {
            var userData = await _userManager.FindByNameAsync(email);
            if (userData == null) { userData = await _userManager.FindByEmailAsync(email); }
            var roleId = 0;
            if (userData.Roles.Any() && userData.Roles.FirstOrDefault() != null)
            {
                roleId = userData.Roles.FirstOrDefault().RoleId;
            }

            CustomIdentityRole role = null;

            if (roleId > 0)
            {
                role = _roleManager.FindById(roleId);
            }

            // Construct ApplicationUser model by getting details of the currently logged in user using OWIN.
            var user = new CustomIdentityUser { Id = userData.Id, UserName = email, Email = email };


            var claimsIdentity = await _signInManager.CreateUserIdentityAsync(user);

            #region Custom Implementation to fetch claims

            //custom implementation            
            List<Tuple<string, string>> configuredClaims = _permissionService.GetClaims(userData.Id);

            List<Claim> claims = new List<Claim>();
            foreach (var c in configuredClaims)
            {
                claims.Add(new Claim(c.Item1, c.Item2));
            }

            claims.Add(new Claim("role", Convert.ToString(role.Name)));
            claims.Add(new Claim("email", email));

            claimsIdentity.AddClaims(claims);
            #endregion

            _authenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = false }, claimsIdentity);

            //return RedirectToAction("Index", "DashBoard", new { area = "Users" });
            return RedirectToLocal(returnUrl);
        }

        // POST: /Account/LogOff
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            _authenticationManager.SignOut();
            return RedirectToAction("Login");
        }


        #region Helpers
        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Dashboard");
        }

        #endregion
    }
}

I2P_LAPP/Areas/Users/Views/WebAccount/ConfirmEmail.cshtml
@{
    ViewBag.Title = "Confirm Email";
}

<h2>@ViewBag.Title.</h2>
<div>
    <p>
        Thank you for confirming your email. Please @Html.ActionLink("Click here to Log in", "Login", "WebAccount", routeValues: null, htmlAttributes: new { id = "loginLink" })
    </p>
</div>

I2P_LAPP/Areas/Users/Views/WebAccount/ExternalLoginConfirmation.cshtml
@model Infinite.LAPP.WebFront.Areas.Users.Models.ExternalLoginConfirmationViewModel
@{
    ViewBag.Title = "Register";
}
<h2>@ViewBag.Title.</h2>
<h3>Associate your @ViewBag.LoginProvider account.</h3>

@using (Html.BeginForm("ExternalLoginConfirmation", "WebAccount", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <h4>Association Form</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <p class="text-info">
        You've successfully authenticated with <strong>@ViewBag.LoginProvider</strong>.
        Please enter a user name for this site below and click the Register button to finish
        logging in.
    </p>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

I2P_LAPP/Areas/Users/Views/WebAccount/ExternalLoginFailure.cshtml
@{
    ViewBag.Title = "Login Failure";
}

<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3 class="text-danger">Unsuccessful login with service.</h3>
</hgroup>

I2P_LAPP/Areas/Users/Views/WebAccount/ForgotPassword.cshtml
@model Infinite.LAPP.WebFront.Areas.Users.Models.ForgotPasswordViewModel
@{
    ViewBag.Title = "Forgot your password?";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("ForgotPassword", "WebAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Enter your email.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Email Link" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

I2P_LAPP/Areas/Users/Views/WebAccount/ForgotPasswordConfirmation.cshtml
@{
    ViewBag.Title = "Forgot Password Confirmation";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>
<div>
    <p>
        Please check your email to reset your password.
    </p>
</div>
	

I2P_LAPP/Areas/Users/Views/WebAccount/Login.cshtml
@using Infinite.LAPP.WebFront.Areas.Users.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .login-val {
        width: 100%;
    }
 .login-val ul {
            margin-left: 0;
            padding: 3px 0 0 5px;
            list-style-type: none;
        }

    .checkbox label, .radio label {
        min-height: 20px;
        padding-left: 5px;
        margin-bottom: 0;
        font-weight: 400;
        cursor: pointer;
    }
</style>

<div class="row">
    <h2 class="align-center">Log in to LAPP</h2>
    <div class="col-md-offset-1 col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "WebAccount", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>@*Use a local account to log in.*@</h4>
                <div class="form-group marb0">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-4 control-label text-left" })
                    <div class="col-md-8">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger login-isreqmsg" })

                    </div>
                </div>
                <div class="form-group marb0">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-4 control-label text-left" })
                    <div class="col-md-8">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger login-isreqmsg" })
                        @Html.ValidationSummary(true, "", new { @class = "text-danger login-val" })
                    </div>
                </div>
               
    <div class="form-group mar-bottom-xlg">
        <div class="pull-right">
            <input type="submit" value="Log in" class="btn btn-primary btn-default" />
        </div>
    </div>

                @*<div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <p>
                                @Html.ActionLink("Register as a new user", "Register")
                            </p>
                        </div>
                    </div>*@

                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

I2P_LAPP/Areas/Users/Views/WebAccount/Register.cshtml
@model Infinite.LAPP.WebFront.Areas.Users.Models.RegisterViewModel
@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Register", "WebAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

I2P_LAPP/Areas/Users/Views/WebAccount/ResetPassword.cshtml
@model Infinite.LAPP.WebFront.Areas.Users.Models.ResetPasswordViewModel
@{
    ViewBag.Title = "Reset password";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("ResetPassword", "WebAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Reset your password.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Code)
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Reset" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

I2P_LAPP/Areas/Users/Views/WebAccount/ResetPasswordConfirmation.cshtml
@{
    ViewBag.Title = "Reset password confirmation";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>
<div>
    <p>
        Your password has been reset. Please @Html.ActionLink("click here to log in", "Login", "WebAccount", routeValues: null, htmlAttributes: new { id = "loginLink" })
    </p>
</div>

I2P_LAPP/Areas/Users/Views/WebAccount/SendCode.cshtml
@model Infinite.LAPP.WebFront.Areas.Users.Models.SendCodeViewModel
@{
    ViewBag.Title = "Send";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("SendCode", "WebAccount", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("rememberMe", @Model.RememberMe)
    <h4>Send verification code</h4>
    <hr />
    <div class="row">
        <div class="col-md-8">
            Select Two-Factor Authentication Provider:
            @Html.DropDownListFor(model => model.SelectedProvider, Model.Providers)
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

I2P_LAPP/Areas/Users/Views/WebAccount/VerifyCode.cshtml
@model Infinite.LAPP.WebFront.Areas.Users.Models.VerifyCodeViewModel
@{
    ViewBag.Title = "Verify";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("VerifyCode", "WebAccount", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("provider", @Model.Provider)
    @Html.Hidden("rememberMe", @Model.RememberMe)
    <h4>Enter verification code</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div class="checkbox">
                @Html.CheckBoxFor(m => m.RememberBrowser)
                @Html.LabelFor(m => m.RememberBrowser)
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

I2P_LAPP/Areas/Users/Views/WebAccount/_ExternalLoginsListPartial.cshtml
@model Infinite.LAPP.WebFront.Areas.Users.Models.ExternalLoginListViewModel
@using Microsoft.Owin.Security

<h4>Use another service to log in.</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {
        <div>
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=403804">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else {
        using (Html.BeginForm("ExternalLogin", "WebAccount", new { ReturnUrl = Model.ReturnUrl }))
        {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in loginProviders) {
                        <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                    }
                </p>
            </div>
        }
    }
}