I2P_LAPP/Areas/Leave/Models/LeaveDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infinite.LAPP.WebFront.Areas.Leave.Models
{
    public class LeaveDetailsViewModel
    {
        public int Id { get; set; }
        public string ApproverComment { get; set; }
        public int Category { get; set; }
        public int EmployeeId { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ReportingMangerId { get; set; }
        public string ReportingManagerName { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public Nullable<int> LeaveRequestStatus { get; set; }
        public int Type { get; set; }
        public string LeaveType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> LeaveRequestDetailsId { get; set; }
        public Nullable<int> DetailsStatus { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}

I2P_LAPP/Areas/Leave/Models/ManageLeavesViewModel.cs
using Infinite.LAPP.Domain;
using Infinite.LAPP.WebFront.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Infinite.LAPP.WebFront.Areas.Leave.Models
{
    public class ManageLeavesViewModel
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public List<Dates> DayList { get; set; }
        public Category Category { get; set; }
        public int EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        [Required(ErrorMessage = ValidationMessages.RequiredValidationMessage)]
        [MaxLength(40, ErrorMessage = "Comment cannot be longer than 40 characters.")]
        public string ApproverComment { get; set; }
        public string ApplierComment { get; set; }
        public string ApproverName { get; set; }
        public LeaveType Type { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public System.DateTime FromDate { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public System.DateTime ToDate { get; set; }
        public int Status { get; set; }
        public int ReportingManagerId { get; set; }
    }

    public class DisplayLeaveRequestDetailsModel 
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public Nullable<System.DateTime> FromDate { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public Nullable<System.DateTime> ToDate { get; set; }
        public LeaveType LeaveType { get; set; }
        public Category Category { get; set; }
        public string CategoryName { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public DateTime CreatedDate { get; set; }
        public string ReportingManagerName { get; set; }
        public bool IsDeleted { get; set; }

    }

    public class ApproveLeaveRequestDetailsModel
    {


        public string EmployeeName { get; set; }
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public Nullable<System.DateTime> FromDate { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public Nullable<System.DateTime> ToDate { get; set; }
        public LeaveType LeaveType { get; set; }
        public Category Category { get; set; }
        public string CategoryName { get; set; }
        public int EmployeeCode { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
        [DisplayFormat(DataFormatString = DisplayFormatConstants.DateFormatString)]
        public DateTime CreatedDate { get; set; }
    }

}

I2P_LAPP/Areas/Leave/Controllers/ManageLeavesController.cs
using Infinite.LAPP.WebFront.Areas.Leave.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Infinite.LAPP.Repository.QueryObjects;
using Infinite.LAPP.WebFront.Controllers;
using AutoMapper;
using Infinite.LAPP.EntityModel;
using Infinite.LAPP.WebFront.MVCInfratructure.MappingLayer;
using Infinite.LAPP.Domain.IRepository;
using Infinite.LAPP.Domain.DomainModel;
using Infinite.LAPP.Domain.Service;
using Infinite.LAPP.WebFront.MVCInfrastructure.ClaimsSecurity;
using System.Security.Permissions;

namespace Infinite.LAPP.WebFront.Areas.Leave.Controllers
{
    public class ManageLeavesController : BaseController
    {
        private LeaveRequestQuery _query = null;
        private LeaveService _leaveRep = null; 

        public ManageLeavesController(LeaveRequestQuery query, LeaveService leaveRep)
        {
            if (leaveRep == null)
                throw new ArgumentNullException("leaveRep is null");
            if (query == null)
                throw new ArgumentNullException("query is null");
            _leaveRep = leaveRep;
            _query = query;

        }

          // GET: Leave/ManageLeaves
        [MappingFilter(typeof(List<vw_GetAllLeavesListForApproval>), typeof(List<ApproveLeaveRequestDetailsModel>))]
        [CustomClaimAttribute(SecurityAction.Demand, Resource = "Leave Management", Value = "canApproveLeave")]
        public ActionResult Index()
        {
            var model = _query.GetAllLeavesByUserId(base.LoggedInUserId);
            return View(model);
        }



        // GET: Leave/ManageLeaves/Details/5
        [MappingFilter(typeof(LeaveRequest), typeof(ManageLeavesViewModel))]
        [CustomClaimAttribute(SecurityAction.Demand, Resource = "Leave Management", Value = "canApproveLeave")]
        public ActionResult LeaveDetails(int leaveRequestId)
        {
            var leaveRequestDetails = _query.GetLeaveRequestById(leaveRequestId);
            return View(leaveRequestDetails);
        }

        public ActionResult ApproveLeave(ManageLeavesViewModel model)
        {
           
            var domainModel = new ApproveLeaveDomainModel()
            {
                LeaveRequestId = model.Id,
                 EmployeeId= model.EmployeeId,
                 DayList= Mapper.Map<List<Dates>,List<DatesDomainModel>>(model.DayList),
                 ApproverComment = model.ApproverComment,
                 Status = 1
            };
            _leaveRep.ApproveLeaveRequest(domainModel);
            return RedirectToAction("Index");

        }

        public ActionResult RejectLeave(int Id, string ApproverComment)
        {
            _leaveRep.RejectLeave(Id, ApproverComment);
            return RedirectToAction("Index");
        }
    }
}

I2P_LAPP/Areas/Leave/Views/ManageLeaves/Index.cshtml
@model List<Infinite.LAPP.WebFront.Areas.Leave.Models.ApproveLeaveRequestDetailsModel>
@using Infinite.LAPP.WebFront.HtmlHelpers
@{
    ViewBag.Title = "Approve/Reject Leave";
}
@section HeaderSection {

    @Html.HeaderSectionHtml("Approve / Reject Leaves")
}


<form>
    <div class="row">
        <div class="col-md-12 mar-top-lg" data-remove-target="p:first">
            <table id="DataGrid"></table>
            <div id="divPager" style="height: auto !important;"></div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        $('.action-nav').remove();
        $('#DataGrid').jqGrid('GridUnload');
        var result = $.parseJSON('@Html.Raw(Json.Encode(Model))');
        popdata(result);
    });

    function popdata(result) {
        $("#DataGrid").jqGrid({
            caption: 'Approve Reject List',
            datatype: "local",
            data: result,
            rowNum: 10,
            gridview: true,
            hidegrid: false,
            pager: '#divPager',
            sortname: 'CreatedDate',
            sortorder: "desc",
            autowidth: true,
            autoencode: true,
            height: 'auto',
            shrinkToFit: false,
            forceFit: true,
            ignoreCase: true,
            sortable: false,
            rownumbers: true,
            colModel: [
                { label: 'Id', name: 'Id', hidden: true },
                    { label: 'Applied By', name: 'EmployeeName', align: "left", search: true, width: 157 },
                    { label: 'Applied On', name: 'CreatedDate', align: "left", formatter: 'date', formatoptions: { newformat: "d/m/Y" }, search: false, width: 110 },
                    { label: 'From Date', name: 'FromDate', align: "left", formatter: 'date', formatoptions: { newformat: "d/m/Y" }, search: false, width: 110 },
                    { label: 'To Date', name: 'ToDate', align: "left", formatter: 'date', formatoptions: { newformat: "d/m/Y" }, search: false, width: 110 },
                    { label: 'Leave Type', name: 'LeaveType', formatter: formatLeaveType, align: "left", search: false, width: 110 },
                    { label: 'Category', name: 'CategoryName', align: "left", search: false, width: 130 },
                    { label: 'Status', name: 'Status', formatter: formatStatus, align: "left", search: false, width: 120 },
                    { label: 'Action', align: "center", formatter: editLinkFormatter, search: false },
            ],
            viewrecords: true, // show the current page, data range and total records on the toolbar
            emptyrecords: 'No records found'
        });
        $('#DataGrid').jqGrid('filterToolbar', { defaultSearch: 'cn' }); // Set Searching
        $("#DataGrid").jqGrid("setLabel", "rn", "No");
    }

    editLinkFormatter = function (cellValue, options, rowObject) {
        var ID = rowObject.Id;
        var url = '@Url.Action("LeaveDetails", "ManageLeaves", new { area = "Leave" })';
        return '<a href=' + url + '?leaveRequestId=' + ID + ' class="fa fa-pencil fa-lg" ></a>';
    }

    formatLeaveType = function (cellvalue, options, rowObject) {
        if (cellvalue == 1)
            return "Planned";
        return "Unplanned";
    }

    formatStatus = function (cellvalue, options, rowObject) {
        if (cellvalue == 1)
            return "Approved";
        else if (cellvalue == 2)
            return "Rejected";
        else
            return "Pending";
    }

</script>

I2P_LAPP/Areas/Leave/Views/ManageLeaves/LeaveDetails.cshtml
@model Infinite.LAPP.WebFront.Areas.Leave.Models.ManageLeavesViewModel

@using Infinite.LAPP.WebFront.HtmlHelpers;
@{
    ViewBag.Title = "Leave Details";
}
@section HeaderSection {

    @Html.HeaderSectionHtml("Approve / Reject Leaves")
}
<script>
    $(document).ready(function () {
        $('.action-nav').remove();
    });
    function RejectLeave() {
        var Id = $('#Id').val();
        $("form").valid()
        var ApproverCommentField = $('#ApproverComment');
        if (ApproverCommentField.val() == "") {
            $('#ApproverCommentError').text("Is Required");
            return false;
        }
        var url = '@Url.Action("RejectLeave", "ManageLeaves" , new{Id = "!", ApproverComment = "parameter"})';
        url = url.replace('!', Id).replace('parameter', ApproverCommentField.val());
        window.location.href = url;
    }

    function form_approve() {
        if (count > 0) {
            if ($("form").valid())
                $("form").submit();
        }
        else {

            DatesError();
        }
    }

    function DatesError() {
        $("#DatesError").dialog({
            autoOpen: true,
            position: { my: "center", at: "top+350", of: window },
            width: 1000,
            resizable: false,
            title: 'Error',
            modal: true,
            open: function () {
                $(this).text("No Dates selected. Form cannot be submitted. Click Ok to Reload page ");
            },
            buttons: {
                "Ok": function () {
                    window.location.reload();
                }
            }
        });
        return false;
    }


</script>

@using (Html.BeginForm("ApproveLeave", "ManageLeaves", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Status)
    <div class="row">
        <div class="col-md-3 mar-top-lg">
            @Html.HiddenFor(x => x.EmployeeName)
            <strong>Applied By:</strong> <span class="pad-left-sm">@Html.DisplayFor(x => x.EmployeeName)</span>
        </div>
        <div class="col-md-3 mar-top-lg">
            @Html.HiddenFor(x => x.Category)
            <strong>Category:</strong> <span class="pad-left-sm">@Html.DisplayFor(x => x.Category)</span>
        </div>
        <div class="col-md-3 mar-top-lg">
            @Html.HiddenFor(x => x.Type)
            <strong>Leave Type:</strong> <span class="pad-left-sm">@Html.DisplayFor(x => x.Type)</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 mar-top-lg">
            <strong>From Date:</strong>
            <span class="pad-left-sm">
                @Html.HiddenFor(x => x.FromDate)
                @Html.DisplayFor(x => x.FromDate)
            </span>
        </div>
        <div class="col-md-3 mar-top-lg">
            <strong>To Date:</strong>
            <span class="pad-left-sm">
                @Html.HiddenFor(x => x.ToDate)
                @Html.DisplayFor(x => x.ToDate)
            </span>
        </div>

    </div>

    <div class="row">
        <div class="col-md-10 mar-top-lg" data-remove-target="p:first">
            @Html.Partial("_ApproveLeaveDetails", Model)
        </div>
    </div>


    @Html.HiddenFor(x => x.Id)
    <div class="row">
        <div class="col-md-4">
            <label>Applier's Comments:</label>
            <div class="form-group">
                @Html.HiddenFor(x => x.ApplierComment)
                @Html.DisplayFor(x => x.ApplierComment)
            </div>
        </div>
        <div class="col-md-4">
            <label>  Comments (Mandatory):</label>
            @if (Model.Status == 0 || Model.Status == null)
            {
             <div class="">
                @Html.TextAreaFor(model => model.ApproverComment, new { @class = "form-control marl0" })
            </div>
            }
            @if (Model.ApproverComment != null)
             {
            <div class="form-group">
                @Html.DisplayFor(model => model.ApproverComment)
            </div>
            }
            @Html.ValidationMessageFor(model => model.ApproverComment, "", new { @class = "text-danger comment-err" })
        </div>
    </div>

    <div id="DatesError" class="messagepop"></div>
    if (Model.Status == 0 || Model.Status == null)
    {
        <div class="pull-left mar-top-lg">
            <button onclick="form_approve()" class="btn btn-primary" type="button">Approve</button>
            <a class="btn btn-primary mar-left-lg" onclick="RejectLeave()" href="#">Reject</a>
        </div>
    }
}